spring:
  application:
    name: e_nanucha_ocpp

  # JPA & Connection Pool
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    url: jdbc:log4jdbc:mysql://127.0.0.1:3307/e_nanucha_ocpp?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 12345%
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
